index:
    path: /index
    controller: App\Controller\DefaultController::index

publish:
    path: /publish
    controller: App\Controller\DefaultController::publish

consume:
    path: /consume
    controller: App\Controller\DefaultController::consume
