version: '2'

services:
#    redis:
#        container_name: container_redis
#        image: redis:alpine
#        ports:
#            - "6379:6379"
    php:
        container_name: container_php
        build:
            context: php7-fpm
#            args:
#                TIMEZONE: sao_paulo
        volumes:
            - ../app:/var/www/symfony
            - ../logs/symfony:/var/www/symfony/var/log
#        links:
#            - redis
    nginx:
        container_name: container_nginx
        build:
            context: nginx
            args:
                MAX_EXECUTION_TIME: 5
                SERVER_NAME: rabbitmq
        ports:
            - "8080:80"
        volumes_from:
            - php
        volumes:
            - ../logs/nginx:/var/log/nginx
        links:
            - rabbit
            - mysql
    mysql:
        container_name: container_mysql
        image: mysql
        volumes:
            - "./.data/mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: rabbitmq
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
    rabbit:
        container_name: container_rabbit
        hostname: rabbit
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        volumes:
            - ../.data/rabbitmq/:/var/lib/rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
#    elk:
#      container_name: container_elk
#      image: sebp/elk
#      volumes:
#          - ./elk/logstash:/etc/logstash
#          - ./elk/logstash/patterns:/opt/logstash/patterns
#          - ./.data/elasticsearch:/var/lib/elasticsearch
##          - ./elk/elasticsearch:/etc/elasticsearch # to place elastisearch.yml configuration
#      volumes_from:
#          - php
#          - nginx
#      ports:
#        - "5601:5601"
#        - "9200:9200"
#        - "5044:5044"
